### ISSUE TITLE
[Document] 참고 자료

### ISSUE THREAD

**Issue by minzero31** [minzero31/MadCamp-1week-Android#1]
1. 안드로이드 스튜디오에서 JSON 활용하기 : https://want-kotlin-pro.tistory.com/243
https://wiki.yowu.dev/ko/Knowledge-base/Kotlin/kotlin-and-json-processing-and-generating-json-data

**Comment by minzero31** [comment]
2. 안드로이드 스튜디오에서 탭 3개 생성하기 : https://gameprograming.tistory.com/140

**Comment by hado68** [comment]
3. Recyclerview에서 LinearLayout을 GridLayout으로 변경하기 : https://velog.io/@simsubeen/Android-Kotlin-RecyclerView-%EA%B0%80%EB%A1%9C-%EC%A0%95%EB%A0%AC-GridLayoutManager

**Comment by hado68** [comment]
4. Recyclerview에서 swipe하면 빨간 버튼이 나타날 수 있도록 하기 : https://velog.io/@chris_seed/AndroidKotlin-RecyclerView%EC%9D%98-%EB%AA%A8%EB%93%A0%EA%B2%83-%EA%B8%B0%EB%B3%B8-%EC%82%AC%EC%9A%A9%EB%B2%95

**Comment by minzero31** [comment]
5. Recyclerview와 button 생성하기 :
https://hyogeun-android.tistory.com/entry/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EA%B0%95%EC%9D%98-10-RecyclerView%EC%99%80-Floating-Action-Button

**Comment by minzero31** [comment]
6. 세 번째 탭 달력 생성하기  
https://velog.io/@rootachieve/%EC%BB%A4%EC%8A%A4%ED%85%80-%EC%BA%98%EB%A6%B0%EB%8D%94-%EB%A7%8C%EB%93%A4%EA%B8%B0-2.%EC%95%84%EC%9D%B4%ED%85%9C-class

**Comment by hado68** [comment]
7. 체크 박스 이벤트 구현
https://recipes4dev.tistory.com/133#google_vignette
