### ISSUE TITLE
[Error] 화면 내에서 각 탭 상단의 공백이 생기는 문제

### ISSUE THREAD

**Issue by minzero31** [minzero31/MadCamp-1week-Android#7]
문제 상황 : 코드 상의 에러가 나지는 않지만 애뮬레이터나 실제 휴대폰에서 run을 시켜보았을 때 탭 별 이름이 나오는 상단 부분과 아래 전화번호가 나오는 부분 / 사진이 나오는 부분 사이의 일정 공간의 공백이 생겨있음. 화면 비율이나 요소들의 위치를 최상단으로 해도 공백이 사라지지 않음.

![image](https://github.com/minzero31/MadCamp-1week-Android/assets/80385982/b4cd0b46-ec8c-4f3b-8994-2f2939bdc6be)

**Comment by hado68** [comment]
activity_main.xml파일에 
"android:paddingTop="?attr/actionBarSize"와 같이 actionbar부분에 상단 padding이 만들어져 있는 것을 찾을 수 있었고, padding을 제거하여 문제를 해결하였다.

![image](https://github.com/minzero31/MadCamp-1week-Android/assets/80385982/e9f26287-cc4a-43e8-9633-0a7c6fcfafe2)

![image](https://github.com/minzero31/MadCamp-1week-Android/assets/154976598/5cce0dc2-ca5c-4dc7-b8b2-8e9b120f56a0)
![image](https://github.com/minzero31/MadCamp-1week-Android/assets/80385982/b9771a34-0bc6-49fa-89c2-035c4c7f09c1)
